app:
  client:
    url: http://localhost:8090
server:
  port: 8090
  shutdown: graceful
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  jackson:
    serialization:
      write-dates-as-timestamps: false
  config:
    activate:
      on-profile: default
    import: "application-secret.yml"
  docker:
    compose:
      enabled: false
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h
  datasource:
    maximum-pool-size: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hoit-database-1.cdogc6048p9x.ap-northeast-2.rds.amazonaws.com:3306/hoit_test?serverTimezone=Asia/Seoul
    username: hoituser
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8090/auth/google/redirect
  rabbitmq:
    host: localhost
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: false
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
# :small_blue_diamond: Actuator 설정 추가 (서버 설정 바로 아래 or 최하단)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.orm.jdbc.bind: INFO
#    org.hibernate.orm.jdbc.extract: INFO
#    org.springframework.transaction.interceptor: INFO
#    org.springframework.security: DEBUG
#    org.springframework.core.env: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari.HikariDataSource: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.web.client: DEBUG
custom:
  webhook-url: https://5332c4322614.ngrok-free.app
  site:
    name: "My Site Prod"

modelslab:
  api:
    key: 3PheOClc1s4G0m0fv89XsEeyPECyqmCr5uAaXBDUAnx1JNVuLBXH6FkbcR0k
    url: https://modelslab.com/api/v6/images/text2img